export { default as About } from './About'
export { default as NotFound } from './NotFound'
export { default as Rank } from './Rank'
export { default as Start } from './Start'
export { default as Main } from './Main'
export { default as My } from './My'
