export { default as Header } from './Common/Header'
export { default as Footer } from './Common/Footer'
export { default as Aside } from './Common/Aside'
export { default as StartPage } from './Start'
export { default as AboutPage } from './AboutPage'
export { default as LoginPage } from './LoginPage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as QuestionPage } from './QuestionPage'
